/**
 * Created by hard on 16-8-27.
 */

export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTE_SUCCESS = 'GET_NOTE_SUCCESS';
export const POST_NOTE_SUCCESS = 'POST_NOTE_SUCCESS';
export const PUT_NOTE_SUCCESS = 'PUT_NOTE_SUCCESS';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';